### ISSUE TITLE
NoMethodError: undefined method `oid' for #<ActiveRecord::ConnectionAdapters::NullColumn>

### ISSUE THREAD

**Issue by azzaahmed** [bjhaid/active_record_bulk_insert#14]
NoMethodError: undefined method `oid' for #<ActiveRecord::ConnectionAdapters::NullColumn:0x00000000081ce578>
/home/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/postgresql/quoting.rb:76:in `lookup_cast_type_from_column'
home/.rvm/gems/ruby-2.4.4/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/quoting.rb:59:in `type_cast_from_column'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:47:in `_bulk_insert_quote'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:28:in `block (2 levels) in bulk_insert'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:27:in `each'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:27:in `map'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:27:in `block in bulk_insert'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:26:in `map'
/home/.rvm/gems/ruby-2.4.4/gems/active_record_bulk_insert-1.3.1/lib/active_record_bulk_insert.rb:26:in `bulk_insert'

**Comment by bjhaid** [comment]
Hey sorry you are encountering this bug, I have not been actively working on this project or related things, however if you identify the root cause and it's related to the project please do submit a patch, I will be happy to review and accept

**Comment by danilvoe** [comment]
We had such a problem when there was a password field in the list of added values (at the DB level it does not exist, but the model has such an attribute) in the User model (connected to the devise) after removing the field the insertion was successful.

rails 5.1.5
